# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99cfbc61cacc4b0fc4928aa5851f471a44ab30fbffe30eaa45a85425af4127f8b6986b6601ba107b32e516a16950632d9771b283f6533b31ad43302d5eb8cc5d

test:
  secret_key_base: 994101c1a1dd9544a8ece5f591bbe6f82969fe5f221ac2d2d33fb85136a19d82aa831a6bba64dd8b9e9fd94ae82bc75bfcf94b4159c2633e60db883bddf9fe59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
